#!/bin/bash
BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(feature-)\w+]"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with '(dev|release)-YYYY-qX.X.X' syntax"
  exit 1
fi
