name: Node change version

on: workflow_dispatch

jobs:
  setup_node:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 7, 8]
        exclude:
          - os: macos-latest
            node_version: 7
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name : Log node version
        run: node -v

