name: Container

on: workflow_dispatch

jobs:
  docker-container:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine3.15
    steps:
      - name: Log container version
        run: |
          node -v
          cat /etc/os-release

  services:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: curl -X POST \
                http://localhost:3001/api/user \
                -H 'Content-Type: application/json' \
                -d '{
              	"username": "hello2222",
              	"address": "dwded"
              	}'
      - name: Get user
        run: curl http://localhost:3001/api/user
