name: Encrypt and decrypt file
on: push

jobs:
  create_decrypted_file:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Decrypt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
             --output $HOME/secrets/decrypted_file.txt decrypted_file.txt.gpg
        env:
          PASSPHRASE: ${{ secrets.DECRYPT_PASSWORD }}
      - name: Print decrypted_file
        run: cat $HOME/secrets/decrypted_file.txt
