name: Node version using matrix strategy

on: workflow_dispatch

jobs:
  example_of_matrix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [7, 6, 8]
        exclude:
          - os: macos-latest
            node_version: 7
    runs-on: ${{matrix.os}}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
      - name: Log node version
        run: node -v
      - name: Log os version
        run: echo "This os is ${{matrix.os}}"
