name: Node change version

on: push

jobs:
  setup_node:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          node_version: [6, 7, 8]
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node_version: ${{ matrix.node_version }}
      - name : Log node version
        run: node -v

